spring.application.name=ProductService

server.port=9091

spring.mongodb.uri=mongodb+srv://vitthalkhemnar:vitthal2003@cluster0.gx2pajj.mongodb.net/ecomproduct?appName=Cluster0
spring.data.mongodb.auto-index-creation=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB